theme: jekyll-theme-minimal
title: ADA Template Website
description: We are going to tell the story of a history teacher passionate about cinema, giving his class about globalization.
show_downloads: True
navigation:
  - title: Globalization and Film industry data story
    url: /
  - title: Example
    url: example
  - title: Economy
    url: economy
  - title: Culture
    url: culture
  - title: Population
    url: population
