theme: jekyll-theme-minimal
title: ADA Template Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Globalization and Film industry data story
    url: /
  - title: Example
    url: example
